trigger:
  branches:
    include:
      - main
pool:
  name: linuxagent1
  demands:
   - agent.name -equals ADO
steps:
 - task: Maven@4
   inputs:
     mavenPomFile: 'pom.xml'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     mavenVersionOption: 'Default'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: false
     
 - task: PowerShell@2
   inputs:
    targetType: 'inline'
    script: |
      Import-Module Microsoft.PowerShell.Security -Force
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      pwd