trigger:
  branches:
    include:
      - main
pool:
  name: SelfAgent
  demands:
   - agent.name -equals SelfAgent
steps:
 - task: Maven@4
   inputs:
     mavenPomFile: 'pom.xml'
     publishJUnitResults: true
     testResultsFiles: '**/surefire-reports/TEST-*.xml'
     javaHomeOption: 'JDKVersion'
     mavenVersionOption: 'Default'
     mavenAuthenticateFeed: false
     effectivePomSkip: false
     sonarQubeRunAnalysis: false

 - script: |
     pwd
     ls -ltr
     echo "running script"